version: '3'

services:
  api:
    image: selosele/selosele2
    container_name: api
    restart: always
    depends_on:
      - db
    ports:
      - "443:${PORT}"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=${NODE_ENV}
      - TS_NODE_TRANSPILE_ONLY=${TS_NODE_TRANSPILE_ONLY}
      - PORT=${PORT}
      - PAGE_ORIGIN=${PAGE_ORIGIN}
      - PRIVATE_KEY_PATH=${PRIVATE_KEY_PATH}
      - CERT_PATH=${CERT_PATH}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_ACCESS_EXPIRATION_TIME=${JWT_ACCESS_EXPIRATION_TIME}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - JWT_REFRESH_SECRET_REDIS_KEY=${JWT_REFRESH_SECRET_REDIS_KEY}
      - JWT_REFRESH_EXPIRATION_TIME=${JWT_REFRESH_EXPIRATION_TIME}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  db:
    image: mariadb:10.6.12
    container_name: db
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

volumes:
  db_volume:
